micronaut:
  application:
    name: keymanager

grpc:
  server:
  port: ${SERVER_PORT:50051}
  keep-alive-time: 1h
  max-inbound-message-size: 1024

datasources:
  default:
    url: ${CONTAINER_DATABASE_URL:`jdbc:mysql://localhost:3306/pix_grpc?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${CONTAINER_DATABASE_USERNAME:root}
    password: ${CONTAINER_DATABASE_PASSWORD:root123MySQL}
    schema-generate: update
    dialect: org.hibernate.dialect.MySQL8Dialect
jpa.default.properties.hibernate.hbm2ddl.auto: update
