apiVersion: v1
kind: Secret
metadata:
  name: orange-talents-05-template-pix-keymanager-grpc-secrets
type: Opaque
data:
  CONTAINER_DATABASE_PASSWORD: {{ .Values.application.CONTAINER_DATABASE_PASSWORD | b64enc | quote  }}